version: "3"
services:
  mosquitto:
    build:
      context: ./mosquitto
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

  mongodb:
    image: mongo
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host

  mqtt-client:
    build:
      context: ../
      dockerfile: Dockerfile # specify the Dockerfile here
    environment:
      - DB_URL=mongodb://mongodb:27017
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883

volumes:
  data:
    name: "mqtt-broker-data"
  mongodb-data:
    name: "mongodb-data"
